;;; gypsum-generate.el --- Theme file generation for Gypsum -*- lexical-binding: t; -*-

;; Copyright (C) 2025

;; Author: Gypsum Contributors
;; Keywords: faces, themes

;; This file is not part of GNU Emacs.

;;; Commentary:

;; Generates Emacs theme files from palettes and face specifications.
;; Produces complete, self-contained `-theme.el' files that can be
;; loaded with `load-theme'.

;;; Code:

(require 'gypsum-palette)
(require 'gypsum-faces)

;; Declared here to avoid circular dependency; gypsum-ui.el is loaded after this
(declare-function gypsum-pick-color "gypsum-ui")

;;; --- Configuration ---

(defcustom gypsum-output-directory
  (expand-file-name "themes" user-emacs-directory)
  "Default directory for generated theme files."
  :type 'directory
  :group 'gypsum)

(defcustom gypsum-author-name nil
  "Author name to include in generated theme headers.
If nil, uses \"Generated by Gypsum\"."
  :type '(choice (const nil) string)
  :group 'gypsum)

;;; --- Color to Variable Mapping ---

(defvar gypsum-generate--color-map nil
  "Alist mapping hex colors to variable names during generation.")

(defun gypsum-generate--build-color-map (palette)
  "Build color map from PALETTE for variable substitution."
  (cl-loop for (key value) on palette by #'cddr
           when (stringp value)
           collect (cons (upcase value)
                         (substring (symbol-name key) 1))))

(defun gypsum-generate--color-to-var (color)
  "Get variable name for COLOR, or return color if not in map."
  (if (and (stringp color) (string-prefix-p "#" color))
      (or (cdr (assoc (upcase color) gypsum-generate--color-map))
          color)
    color))

;;; --- Theme File Generation ---

(defun gypsum-generate--header (name palette)
  "Generate the file header for theme NAME with PALETTE."
  (let ((variant (plist-get palette :variant))
        (contrast (plist-get palette :contrast))
        (seed (plist-get palette :definition))
        (author (or gypsum-author-name "Generated by Gypsum")))
    (format ";;; %s-theme.el --- %s theme -*- lexical-binding: t; -*-

;; Copyright (C) %s

;; Author: %s
;; URL: https://github.com/davidhmartin/gypsum
;; Version: 1.0.0
;; Package-Requires: ((emacs \"24.1\"))
;; Keywords: faces, theme

;; This file is not part of GNU Emacs.

;;; Commentary:

;; An Alabaster-style minimalist theme generated by Gypsum.
;; Follows Nikita Tonsky's philosophy: highlight only what matters.
;;
;; Variant: %s
;; Contrast: %s
;; Seed color: %s
;;
;; Only FOUR semantic categories get color:
;; 1. Strings (%s)
;; 2. Constants (%s)
;; 3. Comments (%s) - prominent, NOT dimmed
;; 4. Definitions (%s)
;;
;; Everything else uses the default foreground. This is intentional.

;;; Code:

"
            name
            (capitalize (format "%s %s theme" name variant))
            (format-time-string "%Y")
            author
            variant
            contrast
            seed
            (plist-get palette :string)
            (plist-get palette :constant)
            (plist-get palette :comment)
            (plist-get palette :definition))))

(defun gypsum-generate--deftheme (name palette)
  "Generate the deftheme form for theme NAME with PALETTE."
  (let ((variant (plist-get palette :variant))
        (contrast (plist-get palette :contrast)))
    (format "(deftheme %s
  \"%s %s%s theme - Alabaster-style minimal highlighting.
Only strings, constants, comments, and definitions get color.\")\n\n"
            name
            (capitalize (symbol-name variant))
            (if (eq contrast 'low) "low-contrast " "")
            name)))

(defun gypsum-generate--palette-let (palette)
  "Generate the let bindings for PALETTE colors."
  (let ((bindings '()))
    (push "(class '((class color) (min-colors 89)))" bindings)
    (cl-loop for (key value) on palette by #'cddr
             when (stringp value)
             do (push (format "(%s %S)"
                              (substring (symbol-name key) 1)
                              value)
                      bindings))
    (concat "(let (" (mapconcat #'identity (nreverse bindings) "\n      ") ")\n\n")))

(defun gypsum-generate--format-value (value)
  "Format VALUE for theme output, using variable references for colors."
  (cond
   ;; Hex color -> variable reference
   ((and (stringp value) (string-prefix-p "#" value))
    (let ((var (gypsum-generate--color-to-var value)))
      (if (string-prefix-p "#" var)
          (format "%S" var)  ; No mapping, use literal
        (format ",%s" var))))
   ;; Boolean
   ((eq value t) "t")
   ((eq value nil) "nil")
   ;; Number
   ((numberp value) (number-to-string value))
   ;; Symbol
   ((symbolp value) (symbol-name value))
   ;; Other
   (t (format "%S" value))))

(defun gypsum-generate--format-box (box-spec)
  "Format BOX-SPEC for theme output."
  (if (and (listp box-spec) (plist-get box-spec :line-width))
      (let ((width (plist-get box-spec :line-width))
            (color (plist-get box-spec :color)))
        (format "(:line-width %d :color %s)"
                width
                (gypsum-generate--format-value color)))
    (format "%S" box-spec)))

(defun gypsum-generate--format-underline (underline-spec)
  "Format UNDERLINE-SPEC for theme output."
  (cond
   ((eq underline-spec t) "t")
   ((null underline-spec) "nil")
   ((and (listp underline-spec) (plist-get underline-spec :style))
    (let ((style (plist-get underline-spec :style))
            (color (plist-get underline-spec :color)))
      (format "(:style %s :color %s)"
              style
              (gypsum-generate--format-value color))))
   (t (format "%S" underline-spec))))

(defun gypsum-generate--format-face-attrs (attrs)
  "Format face ATTRS plist for theme output."
  (let ((parts '()))
    (cl-loop for (key value) on attrs by #'cddr do
             (let ((formatted-value
                    (pcase key
                      (:box (gypsum-generate--format-box value))
                      (:underline (gypsum-generate--format-underline value))
                      (_ (gypsum-generate--format-value value)))))
               (push (format "%s %s" key formatted-value) parts)))
    (concat "(" (mapconcat #'identity (nreverse parts) " ") ")")))

(defun gypsum-generate--format-face-spec (face-spec)
  "Format a single FACE-SPEC for theme output.
FACE-SPEC is (FACE-NAME ((CLASS ATTRS)))."
  (let* ((face-name (car face-spec))
         (class-specs (cadr face-spec))
         (attrs (cadr (car class-specs))))
    (format "   `(%s ((,class %s)))"
            face-name
            (gypsum-generate--format-face-attrs attrs))))

(defun gypsum-generate--footer (name)
  "Generate the file footer for theme NAME."
  (format "

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme '%s)

;;; %s-theme.el ends here
" name name))

(defun gypsum-generate--build-file-content (name palette)
  "Build complete theme file content for NAME with PALETTE."
  (let* ((gypsum-generate--color-map (gypsum-generate--build-color-map palette))
         (face-specs (gypsum-faces-generate palette))
         (face-lines (mapcar #'gypsum-generate--format-face-spec face-specs)))
    (concat
     (gypsum-generate--header name palette)
     (gypsum-generate--deftheme name palette)
     (gypsum-generate--palette-let palette)
     "  (custom-theme-set-faces\n"
     (format "   '%s\n\n" name)
     (mapconcat #'identity face-lines "\n")
     "))"
     (gypsum-generate--footer name))))

(cl-defun gypsum-generate (name &rest args &key _seed _variant _contrast
                                _background _string _constant _comment
                                _definition output load)
  "Generate a theme file with NAME.

Arguments:
  NAME              - Theme name (string, no -theme suffix)

Keyword arguments:
  :seed HEXCOLOR    - Base color (becomes definition), derive others
  :variant SYMBOL   - \\='light or \\='dark (required if no :background)
  :contrast SYMBOL  - \\='normal (default) or \\='low
  :background HEX   - Background color (optional, auto-derived)
  :string HEX       - Override string color
  :constant HEX     - Override constant color
  :comment HEX      - Override comment color
  :definition HEX   - Override definition color (defaults to :seed)
  :output PATH      - Output file path (optional)
  :load BOOL        - Load and enable after generation (default t)

Returns the path to the generated theme file."
  ;; Validate name
  (when (string-suffix-p "-theme" name)
    (setq name (substring name 0 -6)))
  (when (string-empty-p name)
    (error "Theme name cannot be empty"))
  ;; Default :load to t unless explicitly set to nil
  (unless (memq :load args)
    (setq load t))
  ;; Create palette (filter out :output and :load)
  (let* ((palette-args (cl-loop for (k v) on args by #'cddr
                                unless (memq k '(:output :load))
                                append (list k v)))
         (palette (apply #'gypsum-palette-create palette-args))
         (output-path (or output
                          (expand-file-name
                           (format "%s-theme.el" name)
                           gypsum-output-directory)))
         (content (gypsum-generate--build-file-content name palette))
         (theme-sym (intern name)))
    ;; Ensure output directory exists
    (unless (file-directory-p (file-name-directory output-path))
      (make-directory (file-name-directory output-path) t))
    ;; Write file
    (with-temp-file output-path
      (insert content))
    (message "Generated theme: %s" output-path)
    ;; Load and enable if requested
    (when load
      (add-to-list 'custom-theme-load-path (file-name-directory output-path))
      (load-file output-path)
      (load-theme theme-sym t)
      (message "Theme '%s' loaded and enabled" name))
    output-path))

(cl-defun gypsum-generate-all (base-name &rest args &key _seed
                                         _background _string _constant _comment
                                         _definition output-dir load)
  "Generate all 4 theme variants from BASE-NAME.

Creates themes for all combinations of light/dark and normal/low contrast:
  - BASE-NAME-dark       (dark, normal contrast)
  - BASE-NAME-dark-lc    (dark, low contrast)
  - BASE-NAME-light      (light, normal contrast)
  - BASE-NAME-light-lc   (light, low contrast)

Arguments:
  BASE-NAME         - Base theme name (string)

Keyword arguments:
  :seed HEXCOLOR    - Base color (becomes definition), derive others
  :background HEX   - Background color (optional, only used as reference)
  :string HEX       - Override string color
  :constant HEX     - Override constant color
  :comment HEX      - Override comment color
  :definition HEX   - Override definition color (defaults to :seed)
  :output-dir PATH  - Output directory (default: `gypsum-output-directory')
  :load BOOL        - Load themes after generation (default nil for batch)

Returns list of generated theme file paths."
  ;; Validate name
  (when (string-empty-p base-name)
    (error "Theme name cannot be empty"))
  ;; Default :load to nil for batch generation
  (unless (memq :load args)
    (setq load nil))
  ;; Build common args (filter out :output-dir, :load, :variant, :contrast)
  (let* ((common-args (cl-loop for (k v) on args by #'cddr
                               unless (memq k '(:output-dir :load :variant :contrast))
                               append (list k v)))
         (out-dir (or output-dir gypsum-output-directory))
         (variants '((dark . normal)
                     (dark . low)
                     (light . normal)
                     (light . low)))
         (results nil))
    ;; Generate each variant
    (dolist (variant variants)
      (let* ((var-type (car variant))
             (contrast (cdr variant))
             (suffix (if (eq contrast 'low)
                         (format "%s-lc" var-type)
                       (symbol-name var-type)))
             (theme-name (format "%s-%s" base-name suffix))
             (output-path (expand-file-name
                           (format "%s-theme.el" theme-name)
                           out-dir)))
        (apply #'gypsum-generate theme-name
               :variant var-type
               :contrast contrast
               :output output-path
               :load load
               common-args)
        (push output-path results)))
    (message "Generated %d themes in %s" (length results) out-dir)
    (nreverse results)))

(provide 'gypsum-generate)

;;; gypsum-generate.el ends here
